---
title: "R for Data Science: Exercises"
output: html_notebook
---

# Set Up

```{r}
library(tidyverse)
```

# 3 Data Visualisations

#### 3.2.4 Exercises

```{r}
# Looking at the mpg dataset
head(ggplot2::mpg)
```

```{r}
# Run ggplot(data = mpg). What do you see?

ggplot(data = mpg)
```

```{r}
# How many rows are in mpg? How many columns?
df_shape <- dim(mpg)
str_glue("Number of rows: {df_shape[1]} \n Number of columns: {df_shape[2]}")
```

```{r}
# What does the drv variable describe? Read the help for ?mpg to find out.

#?mpg
"drv is the type of drive train, where f = front-wheel drive, r = rear wheel drive, 4 = 4wd"
```

```{r}
# Make a scatterplot of hwy vs cyl.
ggplot(mpg) +
  geom_point(mapping = aes(x = hwy, y = cyl))
```

```{r}
# What happens if you make a scatterplot of class vs drv? Why is the plot not useful?

ggplot(mpg) +
  geom_point(aes(x = class, y = drv))
```

#### 3.3.1 Exercises

```{r}
# What’s gone wrong with this code? Why are the points not blue?

#Ans = the colour parameter should be outside of the aes() function as the aes() function is strictly used for mapping variables to aesthetics.

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
```

```{r}
# Which variables in mpg are categorical? Which variables are continuous? (Hint: type ?mpg to read the documentation for the dataset). How can you see this information when you run mpg?

# Ans =
# Cat: manufactuer, model, year, cyl, trans, drv, fl, class
# Cont: displ, cty, hwy
?mpg
```

```{r}
# Map a continuous variable to color, size, and shape. How do these aesthetics behave differently for categorical vs. continuous variables?

ggplot(mpg) +
  geom_point(mapping = aes(x = class, y = displ, colour = cty
                           ))
```

```{r}
# What happens if you map the same variable to multiple aesthetics?

ggplot(mpg) +
  geom_point(mapping = aes(x = class, y = displ, colour = class
                           ))
```

```{r}
# What does the stroke aesthetic do? What shapes does it work with? (Hint: use ?geom_point)


```

```{r}
# What happens if you map an aesthetic to something other than a variable name, like aes(colour = displ < 5)? Note, you’ll also need to specify x and y.

```
